### ISSUE TITLE
npm start failed after npm install

### ISSUE THREAD

**Issue by Aklilufregzi** [nwutils/nw-angular-cli-example#13]
nw-angular@1.2.0 start: `concurrently "npm run start:web" "wait-on http://localhost:8964 && nw ."`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nw-angular@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by TheJaredWilcurt** [comment]
what is your node/npm version? `node -v` and `npm -v`. You may want to delete your `node_modules` and `package-lock.json` and try `npm install && npm start` again.

The current version of NW.js in this repo is `0.44.4`. It has Node.js `13.10.1` built in. You may find things work easier when the globally installed version of Node matches the version built in to NW.js.
