### ISSUE TITLE
option to see app on web browser

### ISSUE THREAD

**Issue by PortStone** [nwutils/nw-angular-cli-example#2]
Hello, first of all thank you for providing this template. Can you also add an option like npm run start:web so I have the ability to see my angular app on the web browser?

**Comment by TheJaredWilcurt** [comment]
@PortStone I've added a `npm run start:web`. Then you can go to the http://localhost:8964 in any browser. You will, of course, need to conditionally wrap your Desktop-specific code if you want it to run outside of NW.js.

```js
if (window.nw) {
  const fs = require('fs');
  console.log(fs.readdirSync('.'));
}
```
Since browsers do not know Node.js or NW.js commands.
