### ISSUE TITLE
how to use angular 15?

### ISSUE THREAD

**Issue by xingkoo** [nwutils/nw-angular-cli-example#58]
i want to create new application ,base angular new version(v15)

1. `npm install --save-dev nw@sdk concurrently`
2. "start": "concurrently \"ng serve --port=8964\" \"nw .\"", in `/package.json`
3. add this code to `/package.json`.
```
"main": "http://localhost:8964",
"node-remote": "http://localhost:8964",
"window": {
  "width": 960,
  "height": 600,
  "min_width": 700,
  "min_height": 500,
  "icon": "your-app-logo.png"
},
```
4. add this code to `src/index.html`
```
<script>
  window.nw_global = window.global;
  window.global = undefined;
</script>
```
5. **polyfills.ts is removed on angular 15. so?**
6. add this code to `/package.json`
```
  "build": {
    "nwVersion": "v0.55.0",
    "nwFlavor": "normal",
    "targets": [
      "zip",
      "nsis7z"
    ],
    "files": [
      "**/*"
    ],
    "excludes": [
      "e2e/**/*",
      "src/**/*",
      ".editorconfig",
      ".gitignore",
      "angular.json",
      "browserslist",
      "karma.conf.js",
      "package-lock.json",
      "screenshot.png",
      "tsconfig.app.json",
      "tsconfig.json",
      "tsconfig.spec.json",
      "tslint.json"
    ],
    "strippedProperties": [
      "ManifestComments",
      "node-remote",
      "scripts",
      "devDependencies",
      "build"
    ],
    "overriddenProperties": {
      "main": "dist-ng/index.html",
      "node-remote": ""
    },
    "win": {
      "icon": "assets/icon-256.ico"
    },
    "mac": {
      "icon": "assets/icon.icns"
    },
    "nsis": {
      "icon": "assets/icon-256.ico",
      "unIcon": "assets/icon.ico",
      "languages": [
        "English"
      ],
      "diffUpdaters": false,
      "hashCalculation": true
    }
  }
```

pls help me, setp 5 and  Is there anything else that needs to be configured?

**Comment by TheJaredWilcurt** [comment]
I don't actually use Angular (mostly because of TypeScript), so I have no idea. I pieced together this guide based on actual anuglar user's feedback:

* https://dev.to/thejaredwilcurt/angular-cli-and-nwjs-for-development-49gl

Then turned that guide into this repo.

If you can find a way to make 15 work, let me know and I'll update the guide and maybe the repo if I have time. PR's welcome.

**Comment by ayushmanchhabra** [comment]
@xingkoo I'm planning to update it to Angular v16. Would that work for you?

**Comment by ayushmanchhabra** [comment]
@xingkoo I'm new to Angular and am having trouble setting up `ng serve`. I am getting the following error:

```shell
Error: Schema validation failed with the following errors:
  Data path "" must have required property 'browserTarget'.
```

Any idea how to fix this?
