### ISSUE TITLE
How to add sqlite3??

### ISSUE THREAD

**Issue by vatsalkgor** [nwutils/nw-angular-cli-example#6]
I tried to manually compile sqlite3 and add in in the project using `nw-gyp` as described in the sqlite3 installation instructions for node-webkit from [here](https://github.com/mapbox/node-sqlite3#building-for-node-webkit). 

Many of the tutorial say that to use sqlite3, nw and angular together I have to approach like below
Angular -> Express -> sqlite3
Where Angular handles the UI part, using express I create an API and the api endpoints performs the database read write operations. 

I created an express server in the project and started it by adding `"node-main":"path/to/server-startup.js"` in the package.json. Everything works fine until I add sqlite3. The server starts, I can call the api end points from Angular using HttpClient and many other stuff. But as soon as I add sqlite3 in my express app using nw-gyp, i get this error. 

<img width="880" alt="Screen Shot 2020-05-21 at 18 10 10" src="https://user-images.githubusercontent.com/38848916/82529130-6af00e80-9b8e-11ea-9527-059a5726caf9.png">

changes in package.json
```json
"node-main": "api/index.js",
"dependencies": {
    "express": "^4.17.1",
    "sqlite3": "^4.2.0"
  }
"devDependencies:{
    "nw": "0.46.0-sdk",
}
```

Minimal code for api/index.js
```javascript
const sqlite3 = require("sqlite3");

sqlite3.Database("../customeronly1.database", (err) => {
  if (err) {
    console.log(err);
  } else {
    console.log("connected");
  }
});
```
api folder is at the same level as package.json

Any help would be appreciated. Thanks

**Comment by TheJaredWilcurt** [comment]
Closing, unrelated to this repo. You will need to do your own research.

* https://github.com/nwjs/nw.js/wiki/Save-persistent-data-in-app
* https://github.com/nwjs/nw.js/issues?q=is%3Aissue+sqlite3

**Comment by vatsalkgor** [comment]
Thanks for the links. However, I found a better-sqlite3 and used it in the project and everything went well. Posting this as a future reference for someone stuck on the same road.
